# ${project.artifactId} v${project.version}
server-main = "main"
server-queue = "queue"
name = "0b0t"
max-players = 420
message-position = "Position in queue: "
message-connecting = "Connecting to the server..."
message-full = "Server is currently full!"
message-offline = "Server is currently down!"
kick = true
wait-on-kick = 16
